server:
  port: 8082
  tomcat:
    uri-encoding: utf-8


project :
  content: "开发环境"
spring:

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springstudy
    username: root
    password: 123456
    max-active: 20
    max-idle: 8
    min-idle: 8
    initial-size: 10
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
















