spring:
  profiles:
    active: dev

 #公共配置与profiles选择无关 mapperLocations指的路径是src/main/resources 测试
mybatis:
    typeAliasesPackage: com.mybatis.demo.entity
    mapperLocations: classpath:mapper/*.xml
