spring:
  profiles:
    active: dev

###指定SpringBoot监控中心的服务端地址
  boot:
      admin:
        client:
          url: http://localhost:8085


###通过下面的配置启用所有的监控端点，默认情况下，这些端点是禁用的；
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS

 #公共配置与profiles选择无关 mapperLocations指的路径是src/main/resources 测试
mybatis:
    typeAliasesPackage: com.mybatis.demo.entity
    mapperLocations: classpath:mapper/*.xml
